### ISSUE TITLE
Crawler incompatible with post-discovery nucypher

### ISSUE THREAD

**Issue by KPrasch** [nucypher/nucypher-monitor#18]
```
 _____         _ _           
|     |___ ___|_| |_ ___ ___ 
| | | | . |   | |  _| . |  _|
|_|_|_|___|_|_|_|_| |___|_|  

========= Crawler =========

Connecting to preferred teacher nodes...
Traceback (most recent call last):
  File "/home/kieran/.local/share/virtualenvs/nucypher-monitor-Xewuu8ce/bin/nucypher-monitor", line 11, in <module>
    load_entry_point('nucypher-monitor', 'console_scripts', 'nucypher-monitor')()
  File "/home/kieran/.local/share/virtualenvs/nucypher-monitor-Xewuu8ce/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/kieran/.local/share/virtualenvs/nucypher-monitor-Xewuu8ce/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/kieran/.local/share/virtualenvs/nucypher-monitor-Xewuu8ce/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kieran/.local/share/virtualenvs/nucypher-monitor-Xewuu8ce/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kieran/.local/share/virtualenvs/nucypher-monitor-Xewuu8ce/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/kieran/Git/nucypher/nucypher/cli/common_options.py", line 143, in wrapper
    return func(**kwargs)
  File "/home/kieran/Git/nucypher-monitor/monitor/cli/main.py", line 91, in crawl
    blockchain_db_port=influx_port
  File "/home/kieran/Git/nucypher-monitor/monitor/crawler.py", line 137, in __init__
    super().__init__(save_metadata=True, node_storage=node_storage, *args, **kwargs)
  File "/home/kieran/Git/nucypher/nucypher/network/nodes.py", line 354, in __init__
    self.remember_node(node, eager=True)
  File "/home/kieran/Git/nucypher/nucypher/network/nodes.py", line 443, in remember_node
    self.node_storage.store_node_metadata(node=node)
  File "/home/kieran/Git/nucypher/nucypher/config/storages.py", line 308, in store_node_metadata
    self.__write_node_metadata(node)
  File "/home/kieran/Git/nucypher/nucypher/config/storages.py", line 348, in __write_node_metadata
    node.mature()
  File "/home/kieran/Git/nucypher/nucypher/network/nodes.py", line 254, in mature
    mature_node = self.finish()
  File "/home/kieran/.local/share/virtualenvs/nucypher-monitor-Xewuu8ce/lib/python3.7/site-packages/bytestring_splitter/__init__.py", line 53, in finish
    return self._receiver(**finished_values, **self._additional_kwargs)
  File "/home/kieran/Git/nucypher/nucypher/characters/lawful.py", line 1204, in from_processed_bytes
    **processed_objects)
  File "/home/kieran/Git/nucypher/nucypher/characters/base.py", line 355, in from_public_keys
    return cls(is_me=False, crypto_power=crypto_power, *args, **kwargs)
  File "/home/kieran/Git/nucypher/nucypher/characters/lawful.py", line 844, in __init__
    federated_only=self._federated_only_instances,
AttributeError: 'Ursula' object has no attribute '_federated_only_instances'

```

Related to Issue https://github.com/nucypher/nucypher/issues/1570

**Comment by derekpierre** [comment]
Fixed via #34 .
